from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import streamlit as st

from utils import (
    cleanup_result_artifacts,
    DATA_DIR,
    ensure_response_timer,
    get_phase3_question_images,
    get_response_time_seconds,
    init_session,
    render_pdf_in_ui,
    run_model,
    save_to_csv,
    use_phase3_model_defaults,
)
CHECKLIST_TABLE_COLUMNS_BY_WIDTH: dict[int, list[str]] = {
    5: ["Attribute", "Prediction", "State", "Points", "Probability (%)"],
    6: ["Attribute", "Prediction", "State", "Points", "Attr score", "Probability (%)"],
}


def render_phase3_intro() -> None:
    st.set_page_config(page_title="Phase 3", page_icon="🧪", layout="centered")

    init_session()

    st.title("Phase 3: AI Prediction With PDF Explanation")

    st.markdown(
        """
        In Phase 3, each question follows this workflow:

        1. Review the assigned dermoscopic image for that question.
        2. Click **Run inference**.
        3. Review the AI prediction and the explanation PDF generated by the model.
        4. Choose your diagnosis: `Benign` or `Melanoma`.
        5. Set your confidence level from 0% to 100% and submit.
        """
    )

    st.markdown("### How to review the image and explanation")
    st.markdown(
        """
        1. Open a Phase 3 question page from the sidebar or click the button below.
        2. Review the image shown on the page for that question.
        3. Click `Run inference`.
        4. The app will run the model on that question image and generate a prediction with a PDF explanation.
        5. Review the prediction and the PDF explanation shown on the page before submitting your answer.
        """
    )
    st.caption("Phase 3 uses the fixed image set stored in `app/images/phase_3/`.")

    st.markdown("### What stays the same")
    st.markdown(
        """
        - 8 questions
        - 2 diagnosis options: `Benign` and `Melanoma`
        - Confidence slider from 0% to 100%
        """
    )

    if st.button("Go to Phase 3 Question 1", type="primary"):
        st.switch_page("pages/19_Phase_3_Question_1.py")


def render_phase3_question(question_number: int, total_questions: int = 8) -> None:
    st.set_page_config(
        page_title=f"Phase 3 Question {question_number}",
        page_icon="🧪",
        layout="centered",
    )

    init_session()

    st.markdown(
        f"### Phase 3 - Question {question_number}: Review the image, the prediction, and the explanation PDF."
    )
    st.caption(
        "Review the assigned Phase 3 image, run inference, inspect the explanation PDF, then choose your diagnosis and confidence."
    )

    question_key = f"ph3_q{question_number}"
    result_key = f"{question_key}_result"
    timer_key = f"{question_key}_timer"
    ensure_response_timer(timer_key)

    image_paths = get_phase3_question_images(total_questions=total_questions)

    if not image_paths:
        st.error(
            "No supported images found in `app/images/phase_3/`. Please add your dermoscopic images there."
        )
        st.stop()

    if len(image_paths) < question_number:
        st.error(
            f"Not enough supported images found in `app/images/phase_3/` for Question {question_number}. "
            f"Found {len(image_paths)}."
        )
        st.stop()

    image_path = image_paths[question_number - 1]
    st.image(
        image_path,
        caption=f"Question image: {Path(image_path).name}",
        use_container_width=True,
    )

    if st.button(
        "Run inference",
        type="primary",
        key=f"{question_key}_infer",
    ):
        use_phase3_model_defaults()
        with st.spinner("Running inference and generating PDF explanation..."):
            try:
                result = run_model(img_path=image_path, image_name=Path(image_path).name)
            except Exception as exc:
                _clear_phase3_result(question_key)
                st.error(f"Inference failed: {exc}")
            else:
                st.session_state[result_key] = result
                st.success("Inference complete. Prediction and explanation are ready.")

    result = st.session_state.get(result_key)
    if result:
        _render_phase3_prediction(result)
    else:
        st.warning("Run inference to view the AI prediction and explanation before submitting your answer.")

    answer = st.radio(
        "Diagnosis",
        ["Benign", "Melanoma"],
        horizontal=True,
        label_visibility="collapsed",
        key=f"{question_key}_answer_input",
        disabled=result is None,
    )

    st.markdown("#### Confidence level")
    confidence = st.slider(
        "How confident are you in your answer? (0% = not confident, 100% = very confident)",
        min_value=0,
        max_value=100,
        value=50,
        step=1,
        key=f"{question_key}_confidence_input",
        disabled=result is None,
    )

    if st.button(
        "Submit",
        type="primary",
        key=f"{question_key}_submit",
        disabled=result is None,
    ):
        st.session_state[f"{question_key}_answer"] = answer
        st.session_state[f"{question_key}_confidence"] = confidence

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        response_time_seconds = get_response_time_seconds(timer_key, reset=True)
        name = st.session_state.get("name")
        email = st.session_state.get("email")
        headers = [
            "Timestamp",
            "Name",
            "Email",
            "Question",
            "UploadedImage",
            "ModelPrediction",
            "ModelMelanomaRisk",
            "ExplanationPdf",
            "Answer",
            "Confidence",
            "ResponseTimeSeconds",
        ]
        save_to_csv(
            DATA_DIR / "phase3_responses.csv",
            [
                timestamp,
                name,
                email,
                f"PH3_Q{question_number}",
                Path(image_path).name,
                result.get("prediction"),
                _format_risk(result.get("prob_melanoma")),
                None,
                answer,
                confidence,
                response_time_seconds,
            ],
            headers,
        )
        cleanup_result_artifacts(result)

        if question_number < total_questions:
            st.success("Saved your answer. Use the sidebar to continue to the next Phase 3 question.")
        else:
            st.success("Saved your answer. Phase 3 is complete. Use the sidebar to continue to Phase 4.")


def _render_phase3_prediction(result: dict[str, Any]) -> None:
    st.markdown("#### AI prediction")
    st.markdown(
        "### The model suggests further assessment if the total dermoscopic score is equal or greater than 3."
    )

    prediction = result.get("prediction") or "Unavailable"
    st.success(f"Prediction: {prediction}")

    prob_melanoma = result.get("prob_melanoma")
    if isinstance(prob_melanoma, (int, float)):
        st.caption(f"Estimated melanoma risk: {float(prob_melanoma) * 100:.1f}%")

    explanation_image = result.get("explanation_image")
    if explanation_image:
        st.markdown("#### Explanation preview")
        st.image(
            explanation_image,
            caption="Explanation preview generated from the model output",
            use_container_width=True,
        )

    checklist_table = result.get("checklist_table")
    table_rows = _normalize_checklist_table_rows(checklist_table)
    if table_rows:
        st.markdown("#### Attribute scores")
        st.dataframe(
            table_rows,
            hide_index=True,
            use_container_width=True,
        )

    st.markdown("#### Explanation PDF")
    explanation_pdf = result.get("explanation_pdf")
    if explanation_pdf:
        pdf_path = Path(explanation_pdf)
        if pdf_path.exists():
            st.download_button(
                "Download explanation PDF",
                data=pdf_path.read_bytes(),
                file_name=pdf_path.name,
                mime="application/pdf",
                key=f"download_{pdf_path.stem}",
            )
        else:
            st.warning(f"Explanation PDF not found: {pdf_path}")
    else:
        st.warning("No explanation PDF was returned for this inference.")


def _clear_phase3_result(question_key: str) -> None:
    result = st.session_state.pop(f"{question_key}_result", None)
    cleanup_result_artifacts(result)


def _format_risk(value: Any) -> str | None:
    if isinstance(value, (int, float)):
        return f"{float(value) * 100:.1f}%"
    return None


def _normalize_checklist_table_rows(checklist_table: Any) -> list[dict[str, Any]]:
    if not isinstance(checklist_table, list) or not checklist_table:
        return []

    first_row = checklist_table[0]
    if isinstance(first_row, dict):
        return [row for row in checklist_table if isinstance(row, dict)]

    if not isinstance(first_row, (list, tuple)):
        return []

    headers = CHECKLIST_TABLE_COLUMNS_BY_WIDTH.get(len(first_row))
    if not headers:
        return []

    rows: list[dict[str, Any]] = []
    for row in checklist_table:
        if not isinstance(row, (list, tuple)):
            continue
        values = list(row[: len(headers)])
        if len(values) < len(headers):
            values.extend([None] * (len(headers) - len(values)))
        rows.append(dict(zip(headers, values)))
    return rows
